//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diem
    {
        public int MaDiem { get; set; }
        public int MaSinhVien { get; set; }
        public string MonHoc { get; set; }
        public double DiemSo { get; set; }
    
        public virtual SinhVien SinhVien { get; set; }
    }
}
