//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManage
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLySinhVienEntities : DbContext
    {
        public QuanLySinhVienEntities()
            : base("name=QuanLySinhVienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Diem>()
                .HasRequired(d => d.SinhVien) // Ràng buộc bắt buộc
                .WithMany(s => s.Diems)       // Quan hệ 1-N
                .HasForeignKey(d => d.MaSinhVien)
                .WillCascadeOnDelete(true);  // Bật cascade delete
        }
    
        public virtual DbSet<Diem> Diems { get; set; }
        public virtual DbSet<SinhVien> SinhViens { get; set; }
    }
}
